//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace PanoramaApp3.ServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tbl_User", Namespace="http://schemas.datacontract.org/2004/07/Wcf")]
    public partial class Tbl_User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AdresField;
        
        private string GebruikersnaamField;
        
        private int IDField;
        
        private string NaamField;
        
        private int NummerField;
        
        private string PaswoordField;
        
        private string PlaatsField;
        
        private int PostcodeField;
        
        private int Rechten_IDField;
        
        private string VoornaamField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gebruikersnaam {
            get {
                return this.GebruikersnaamField;
            }
            set {
                if ((object.ReferenceEquals(this.GebruikersnaamField, value) != true)) {
                    this.GebruikersnaamField = value;
                    this.RaisePropertyChanged("Gebruikersnaam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naam {
            get {
                return this.NaamField;
            }
            set {
                if ((object.ReferenceEquals(this.NaamField, value) != true)) {
                    this.NaamField = value;
                    this.RaisePropertyChanged("Naam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nummer {
            get {
                return this.NummerField;
            }
            set {
                if ((this.NummerField.Equals(value) != true)) {
                    this.NummerField = value;
                    this.RaisePropertyChanged("Nummer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paswoord {
            get {
                return this.PaswoordField;
            }
            set {
                if ((object.ReferenceEquals(this.PaswoordField, value) != true)) {
                    this.PaswoordField = value;
                    this.RaisePropertyChanged("Paswoord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Plaats {
            get {
                return this.PlaatsField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaatsField, value) != true)) {
                    this.PlaatsField = value;
                    this.RaisePropertyChanged("Plaats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((this.PostcodeField.Equals(value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rechten_ID {
            get {
                return this.Rechten_IDField;
            }
            set {
                if ((this.Rechten_IDField.Equals(value) != true)) {
                    this.Rechten_IDField = value;
                    this.RaisePropertyChanged("Rechten_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Voornaam {
            get {
                return this.VoornaamField;
            }
            set {
                if ((object.ReferenceEquals(this.VoornaamField, value) != true)) {
                    this.VoornaamField = value;
                    this.RaisePropertyChanged("Voornaam");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Activities", Namespace="http://schemas.datacontract.org/2004/07/Wcf")]
    public partial class Activities : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ActiviteitField;
        
        private int Activiteit_IDField;
        
        private string CategorieField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Activiteit {
            get {
                return this.ActiviteitField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiviteitField, value) != true)) {
                    this.ActiviteitField = value;
                    this.RaisePropertyChanged("Activiteit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Activiteit_ID {
            get {
                return this.Activiteit_IDField;
            }
            set {
                if ((this.Activiteit_IDField.Equals(value) != true)) {
                    this.Activiteit_IDField = value;
                    this.RaisePropertyChanged("Activiteit_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categorie {
            get {
                return this.CategorieField;
            }
            set {
                if ((object.ReferenceEquals(this.CategorieField, value) != true)) {
                    this.CategorieField = value;
                    this.RaisePropertyChanged("Categorie");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tbl_Categorien", Namespace="http://schemas.datacontract.org/2004/07/Wcf")]
    public partial class Tbl_Categorien : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string OmschrijvingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Omschrijving {
            get {
                return this.OmschrijvingField;
            }
            set {
                if ((object.ReferenceEquals(this.OmschrijvingField, value) != true)) {
                    this.OmschrijvingField = value;
                    this.RaisePropertyChanged("Omschrijving");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetUser", ReplyAction="http://tempuri.org/IService/GetUserResponse")]
        System.IAsyncResult BeginGetUser(int ID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_User> EndGetUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetAllUsers", ReplyAction="http://tempuri.org/IService/GetAllUsersResponse")]
        System.IAsyncResult BeginGetAllUsers(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_User> EndGetAllUsers(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetAllActivities", ReplyAction="http://tempuri.org/IService/GetAllActivitiesResponse")]
        System.IAsyncResult BeginGetAllActivities(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Activities> EndGetAllActivities(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/GetAllCategories", ReplyAction="http://tempuri.org/IService/GetAllCategoriesResponse")]
        System.IAsyncResult BeginGetAllCategories(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_Categorien> EndGetAllCategories(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/SigninUser", ReplyAction="http://tempuri.org/IService/SigninUserResponse")]
        System.IAsyncResult BeginSigninUser(string uname, string pass, System.AsyncCallback callback, object asyncState);
        
        int EndSigninUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/AddUser", ReplyAction="http://tempuri.org/IService/AddUserResponse")]
        System.IAsyncResult BeginAddUser(string naam, string voornaam, string adres, int nummer, string plaats, int postcode, string gebruikersn, string pasw, System.AsyncCallback callback, object asyncState);
        
        void EndAddUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/AddActivity", ReplyAction="http://tempuri.org/IService/AddActivityResponse")]
        System.IAsyncResult BeginAddActivity(string omschr, int catid, System.AsyncCallback callback, object asyncState);
        
        void EndAddActivity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/AddCategory", ReplyAction="http://tempuri.org/IService/AddCategoryResponse")]
        System.IAsyncResult BeginAddCategory(string omschr, System.AsyncCallback callback, object asyncState);
        
        void EndAddCategory(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService/DeleteActivity", ReplyAction="http://tempuri.org/IService/DeleteActivityResponse")]
        System.IAsyncResult BeginDeleteActivity(int id, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteActivity(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : PanoramaApp3.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_User> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_User>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_User> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_User>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllActivitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllActivitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Activities> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Activities>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_Categorien> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_Categorien>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SigninUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SigninUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<PanoramaApp3.ServiceReference.IService>, PanoramaApp3.ServiceReference.IService {
        
        private BeginOperationDelegate onBeginGetUserDelegate;
        
        private EndOperationDelegate onEndGetUserDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllUsersDelegate;
        
        private EndOperationDelegate onEndGetAllUsersDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllUsersCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllActivitiesDelegate;
        
        private EndOperationDelegate onEndGetAllActivitiesDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllActivitiesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllCategoriesDelegate;
        
        private EndOperationDelegate onEndGetAllCategoriesDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllCategoriesCompletedDelegate;
        
        private BeginOperationDelegate onBeginSigninUserDelegate;
        
        private EndOperationDelegate onEndSigninUserDelegate;
        
        private System.Threading.SendOrPostCallback onSigninUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddUserDelegate;
        
        private EndOperationDelegate onEndAddUserDelegate;
        
        private System.Threading.SendOrPostCallback onAddUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddActivityDelegate;
        
        private EndOperationDelegate onEndAddActivityDelegate;
        
        private System.Threading.SendOrPostCallback onAddActivityCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddCategoryDelegate;
        
        private EndOperationDelegate onEndAddCategoryDelegate;
        
        private System.Threading.SendOrPostCallback onAddCategoryCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteActivityDelegate;
        
        private EndOperationDelegate onEndDeleteActivityDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteActivityCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetUserCompletedEventArgs> GetUserCompleted;
        
        public event System.EventHandler<GetAllUsersCompletedEventArgs> GetAllUsersCompleted;
        
        public event System.EventHandler<GetAllActivitiesCompletedEventArgs> GetAllActivitiesCompleted;
        
        public event System.EventHandler<GetAllCategoriesCompletedEventArgs> GetAllCategoriesCompleted;
        
        public event System.EventHandler<SigninUserCompletedEventArgs> SigninUserCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddUserCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddActivityCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddCategoryCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteActivityCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PanoramaApp3.ServiceReference.IService.BeginGetUser(int ID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUser(ID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_User> PanoramaApp3.ServiceReference.IService.EndGetUser(System.IAsyncResult result) {
            return base.Channel.EndGetUser(result);
        }
        
        private System.IAsyncResult OnBeginGetUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int ID = ((int)(inValues[0]));
            return ((PanoramaApp3.ServiceReference.IService)(this)).BeginGetUser(ID, callback, asyncState);
        }
        
        private object[] OnEndGetUser(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_User> retVal = ((PanoramaApp3.ServiceReference.IService)(this)).EndGetUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserCompleted(object state) {
            if ((this.GetUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserCompleted(this, new GetUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserAsync(int ID) {
            this.GetUserAsync(ID, null);
        }
        
        public void GetUserAsync(int ID, object userState) {
            if ((this.onBeginGetUserDelegate == null)) {
                this.onBeginGetUserDelegate = new BeginOperationDelegate(this.OnBeginGetUser);
            }
            if ((this.onEndGetUserDelegate == null)) {
                this.onEndGetUserDelegate = new EndOperationDelegate(this.OnEndGetUser);
            }
            if ((this.onGetUserCompletedDelegate == null)) {
                this.onGetUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserDelegate, new object[] {
                        ID}, this.onEndGetUserDelegate, this.onGetUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PanoramaApp3.ServiceReference.IService.BeginGetAllUsers(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllUsers(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_User> PanoramaApp3.ServiceReference.IService.EndGetAllUsers(System.IAsyncResult result) {
            return base.Channel.EndGetAllUsers(result);
        }
        
        private System.IAsyncResult OnBeginGetAllUsers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PanoramaApp3.ServiceReference.IService)(this)).BeginGetAllUsers(callback, asyncState);
        }
        
        private object[] OnEndGetAllUsers(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_User> retVal = ((PanoramaApp3.ServiceReference.IService)(this)).EndGetAllUsers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllUsersCompleted(object state) {
            if ((this.GetAllUsersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllUsersCompleted(this, new GetAllUsersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllUsersAsync() {
            this.GetAllUsersAsync(null);
        }
        
        public void GetAllUsersAsync(object userState) {
            if ((this.onBeginGetAllUsersDelegate == null)) {
                this.onBeginGetAllUsersDelegate = new BeginOperationDelegate(this.OnBeginGetAllUsers);
            }
            if ((this.onEndGetAllUsersDelegate == null)) {
                this.onEndGetAllUsersDelegate = new EndOperationDelegate(this.OnEndGetAllUsers);
            }
            if ((this.onGetAllUsersCompletedDelegate == null)) {
                this.onGetAllUsersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllUsersCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllUsersDelegate, null, this.onEndGetAllUsersDelegate, this.onGetAllUsersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PanoramaApp3.ServiceReference.IService.BeginGetAllActivities(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllActivities(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Activities> PanoramaApp3.ServiceReference.IService.EndGetAllActivities(System.IAsyncResult result) {
            return base.Channel.EndGetAllActivities(result);
        }
        
        private System.IAsyncResult OnBeginGetAllActivities(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PanoramaApp3.ServiceReference.IService)(this)).BeginGetAllActivities(callback, asyncState);
        }
        
        private object[] OnEndGetAllActivities(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Activities> retVal = ((PanoramaApp3.ServiceReference.IService)(this)).EndGetAllActivities(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllActivitiesCompleted(object state) {
            if ((this.GetAllActivitiesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllActivitiesCompleted(this, new GetAllActivitiesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllActivitiesAsync() {
            this.GetAllActivitiesAsync(null);
        }
        
        public void GetAllActivitiesAsync(object userState) {
            if ((this.onBeginGetAllActivitiesDelegate == null)) {
                this.onBeginGetAllActivitiesDelegate = new BeginOperationDelegate(this.OnBeginGetAllActivities);
            }
            if ((this.onEndGetAllActivitiesDelegate == null)) {
                this.onEndGetAllActivitiesDelegate = new EndOperationDelegate(this.OnEndGetAllActivities);
            }
            if ((this.onGetAllActivitiesCompletedDelegate == null)) {
                this.onGetAllActivitiesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllActivitiesCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllActivitiesDelegate, null, this.onEndGetAllActivitiesDelegate, this.onGetAllActivitiesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PanoramaApp3.ServiceReference.IService.BeginGetAllCategories(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllCategories(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_Categorien> PanoramaApp3.ServiceReference.IService.EndGetAllCategories(System.IAsyncResult result) {
            return base.Channel.EndGetAllCategories(result);
        }
        
        private System.IAsyncResult OnBeginGetAllCategories(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PanoramaApp3.ServiceReference.IService)(this)).BeginGetAllCategories(callback, asyncState);
        }
        
        private object[] OnEndGetAllCategories(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_Categorien> retVal = ((PanoramaApp3.ServiceReference.IService)(this)).EndGetAllCategories(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllCategoriesCompleted(object state) {
            if ((this.GetAllCategoriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllCategoriesCompleted(this, new GetAllCategoriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllCategoriesAsync() {
            this.GetAllCategoriesAsync(null);
        }
        
        public void GetAllCategoriesAsync(object userState) {
            if ((this.onBeginGetAllCategoriesDelegate == null)) {
                this.onBeginGetAllCategoriesDelegate = new BeginOperationDelegate(this.OnBeginGetAllCategories);
            }
            if ((this.onEndGetAllCategoriesDelegate == null)) {
                this.onEndGetAllCategoriesDelegate = new EndOperationDelegate(this.OnEndGetAllCategories);
            }
            if ((this.onGetAllCategoriesCompletedDelegate == null)) {
                this.onGetAllCategoriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllCategoriesCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllCategoriesDelegate, null, this.onEndGetAllCategoriesDelegate, this.onGetAllCategoriesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PanoramaApp3.ServiceReference.IService.BeginSigninUser(string uname, string pass, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSigninUser(uname, pass, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int PanoramaApp3.ServiceReference.IService.EndSigninUser(System.IAsyncResult result) {
            return base.Channel.EndSigninUser(result);
        }
        
        private System.IAsyncResult OnBeginSigninUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string uname = ((string)(inValues[0]));
            string pass = ((string)(inValues[1]));
            return ((PanoramaApp3.ServiceReference.IService)(this)).BeginSigninUser(uname, pass, callback, asyncState);
        }
        
        private object[] OnEndSigninUser(System.IAsyncResult result) {
            int retVal = ((PanoramaApp3.ServiceReference.IService)(this)).EndSigninUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSigninUserCompleted(object state) {
            if ((this.SigninUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SigninUserCompleted(this, new SigninUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SigninUserAsync(string uname, string pass) {
            this.SigninUserAsync(uname, pass, null);
        }
        
        public void SigninUserAsync(string uname, string pass, object userState) {
            if ((this.onBeginSigninUserDelegate == null)) {
                this.onBeginSigninUserDelegate = new BeginOperationDelegate(this.OnBeginSigninUser);
            }
            if ((this.onEndSigninUserDelegate == null)) {
                this.onEndSigninUserDelegate = new EndOperationDelegate(this.OnEndSigninUser);
            }
            if ((this.onSigninUserCompletedDelegate == null)) {
                this.onSigninUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSigninUserCompleted);
            }
            base.InvokeAsync(this.onBeginSigninUserDelegate, new object[] {
                        uname,
                        pass}, this.onEndSigninUserDelegate, this.onSigninUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PanoramaApp3.ServiceReference.IService.BeginAddUser(string naam, string voornaam, string adres, int nummer, string plaats, int postcode, string gebruikersn, string pasw, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddUser(naam, voornaam, adres, nummer, plaats, postcode, gebruikersn, pasw, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PanoramaApp3.ServiceReference.IService.EndAddUser(System.IAsyncResult result) {
            base.Channel.EndAddUser(result);
        }
        
        private System.IAsyncResult OnBeginAddUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string naam = ((string)(inValues[0]));
            string voornaam = ((string)(inValues[1]));
            string adres = ((string)(inValues[2]));
            int nummer = ((int)(inValues[3]));
            string plaats = ((string)(inValues[4]));
            int postcode = ((int)(inValues[5]));
            string gebruikersn = ((string)(inValues[6]));
            string pasw = ((string)(inValues[7]));
            return ((PanoramaApp3.ServiceReference.IService)(this)).BeginAddUser(naam, voornaam, adres, nummer, plaats, postcode, gebruikersn, pasw, callback, asyncState);
        }
        
        private object[] OnEndAddUser(System.IAsyncResult result) {
            ((PanoramaApp3.ServiceReference.IService)(this)).EndAddUser(result);
            return null;
        }
        
        private void OnAddUserCompleted(object state) {
            if ((this.AddUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddUserAsync(string naam, string voornaam, string adres, int nummer, string plaats, int postcode, string gebruikersn, string pasw) {
            this.AddUserAsync(naam, voornaam, adres, nummer, plaats, postcode, gebruikersn, pasw, null);
        }
        
        public void AddUserAsync(string naam, string voornaam, string adres, int nummer, string plaats, int postcode, string gebruikersn, string pasw, object userState) {
            if ((this.onBeginAddUserDelegate == null)) {
                this.onBeginAddUserDelegate = new BeginOperationDelegate(this.OnBeginAddUser);
            }
            if ((this.onEndAddUserDelegate == null)) {
                this.onEndAddUserDelegate = new EndOperationDelegate(this.OnEndAddUser);
            }
            if ((this.onAddUserCompletedDelegate == null)) {
                this.onAddUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddUserCompleted);
            }
            base.InvokeAsync(this.onBeginAddUserDelegate, new object[] {
                        naam,
                        voornaam,
                        adres,
                        nummer,
                        plaats,
                        postcode,
                        gebruikersn,
                        pasw}, this.onEndAddUserDelegate, this.onAddUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PanoramaApp3.ServiceReference.IService.BeginAddActivity(string omschr, int catid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddActivity(omschr, catid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PanoramaApp3.ServiceReference.IService.EndAddActivity(System.IAsyncResult result) {
            base.Channel.EndAddActivity(result);
        }
        
        private System.IAsyncResult OnBeginAddActivity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string omschr = ((string)(inValues[0]));
            int catid = ((int)(inValues[1]));
            return ((PanoramaApp3.ServiceReference.IService)(this)).BeginAddActivity(omschr, catid, callback, asyncState);
        }
        
        private object[] OnEndAddActivity(System.IAsyncResult result) {
            ((PanoramaApp3.ServiceReference.IService)(this)).EndAddActivity(result);
            return null;
        }
        
        private void OnAddActivityCompleted(object state) {
            if ((this.AddActivityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddActivityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddActivityAsync(string omschr, int catid) {
            this.AddActivityAsync(omschr, catid, null);
        }
        
        public void AddActivityAsync(string omschr, int catid, object userState) {
            if ((this.onBeginAddActivityDelegate == null)) {
                this.onBeginAddActivityDelegate = new BeginOperationDelegate(this.OnBeginAddActivity);
            }
            if ((this.onEndAddActivityDelegate == null)) {
                this.onEndAddActivityDelegate = new EndOperationDelegate(this.OnEndAddActivity);
            }
            if ((this.onAddActivityCompletedDelegate == null)) {
                this.onAddActivityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddActivityCompleted);
            }
            base.InvokeAsync(this.onBeginAddActivityDelegate, new object[] {
                        omschr,
                        catid}, this.onEndAddActivityDelegate, this.onAddActivityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PanoramaApp3.ServiceReference.IService.BeginAddCategory(string omschr, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddCategory(omschr, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PanoramaApp3.ServiceReference.IService.EndAddCategory(System.IAsyncResult result) {
            base.Channel.EndAddCategory(result);
        }
        
        private System.IAsyncResult OnBeginAddCategory(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string omschr = ((string)(inValues[0]));
            return ((PanoramaApp3.ServiceReference.IService)(this)).BeginAddCategory(omschr, callback, asyncState);
        }
        
        private object[] OnEndAddCategory(System.IAsyncResult result) {
            ((PanoramaApp3.ServiceReference.IService)(this)).EndAddCategory(result);
            return null;
        }
        
        private void OnAddCategoryCompleted(object state) {
            if ((this.AddCategoryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddCategoryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddCategoryAsync(string omschr) {
            this.AddCategoryAsync(omschr, null);
        }
        
        public void AddCategoryAsync(string omschr, object userState) {
            if ((this.onBeginAddCategoryDelegate == null)) {
                this.onBeginAddCategoryDelegate = new BeginOperationDelegate(this.OnBeginAddCategory);
            }
            if ((this.onEndAddCategoryDelegate == null)) {
                this.onEndAddCategoryDelegate = new EndOperationDelegate(this.OnEndAddCategory);
            }
            if ((this.onAddCategoryCompletedDelegate == null)) {
                this.onAddCategoryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddCategoryCompleted);
            }
            base.InvokeAsync(this.onBeginAddCategoryDelegate, new object[] {
                        omschr}, this.onEndAddCategoryDelegate, this.onAddCategoryCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PanoramaApp3.ServiceReference.IService.BeginDeleteActivity(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteActivity(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void PanoramaApp3.ServiceReference.IService.EndDeleteActivity(System.IAsyncResult result) {
            base.Channel.EndDeleteActivity(result);
        }
        
        private System.IAsyncResult OnBeginDeleteActivity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((PanoramaApp3.ServiceReference.IService)(this)).BeginDeleteActivity(id, callback, asyncState);
        }
        
        private object[] OnEndDeleteActivity(System.IAsyncResult result) {
            ((PanoramaApp3.ServiceReference.IService)(this)).EndDeleteActivity(result);
            return null;
        }
        
        private void OnDeleteActivityCompleted(object state) {
            if ((this.DeleteActivityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteActivityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteActivityAsync(int id) {
            this.DeleteActivityAsync(id, null);
        }
        
        public void DeleteActivityAsync(int id, object userState) {
            if ((this.onBeginDeleteActivityDelegate == null)) {
                this.onBeginDeleteActivityDelegate = new BeginOperationDelegate(this.OnBeginDeleteActivity);
            }
            if ((this.onEndDeleteActivityDelegate == null)) {
                this.onEndDeleteActivityDelegate = new EndOperationDelegate(this.OnEndDeleteActivity);
            }
            if ((this.onDeleteActivityCompletedDelegate == null)) {
                this.onDeleteActivityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteActivityCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteActivityDelegate, new object[] {
                        id}, this.onEndDeleteActivityDelegate, this.onDeleteActivityCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PanoramaApp3.ServiceReference.IService CreateChannel() {
            return new ServiceClientChannel(this);
        }
        
        private class ServiceClientChannel : ChannelBase<PanoramaApp3.ServiceReference.IService>, PanoramaApp3.ServiceReference.IService {
            
            public ServiceClientChannel(System.ServiceModel.ClientBase<PanoramaApp3.ServiceReference.IService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetUser(int ID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ID;
                System.IAsyncResult _result = base.BeginInvoke("GetUser", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_User> EndGetUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_User> _result = ((System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_User>)(base.EndInvoke("GetUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllUsers(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllUsers", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_User> EndGetAllUsers(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_User> _result = ((System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_User>)(base.EndInvoke("GetAllUsers", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllActivities(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllActivities", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Activities> EndGetAllActivities(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Activities> _result = ((System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Activities>)(base.EndInvoke("GetAllActivities", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllCategories(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllCategories", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_Categorien> EndGetAllCategories(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_Categorien> _result = ((System.Collections.ObjectModel.ObservableCollection<PanoramaApp3.ServiceReference.Tbl_Categorien>)(base.EndInvoke("GetAllCategories", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSigninUser(string uname, string pass, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = uname;
                _args[1] = pass;
                System.IAsyncResult _result = base.BeginInvoke("SigninUser", _args, callback, asyncState);
                return _result;
            }
            
            public int EndSigninUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("SigninUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddUser(string naam, string voornaam, string adres, int nummer, string plaats, int postcode, string gebruikersn, string pasw, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[8];
                _args[0] = naam;
                _args[1] = voornaam;
                _args[2] = adres;
                _args[3] = nummer;
                _args[4] = plaats;
                _args[5] = postcode;
                _args[6] = gebruikersn;
                _args[7] = pasw;
                System.IAsyncResult _result = base.BeginInvoke("AddUser", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddUser", _args, result);
            }
            
            public System.IAsyncResult BeginAddActivity(string omschr, int catid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = omschr;
                _args[1] = catid;
                System.IAsyncResult _result = base.BeginInvoke("AddActivity", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddActivity(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddActivity", _args, result);
            }
            
            public System.IAsyncResult BeginAddCategory(string omschr, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = omschr;
                System.IAsyncResult _result = base.BeginInvoke("AddCategory", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddCategory(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddCategory", _args, result);
            }
            
            public System.IAsyncResult BeginDeleteActivity(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("DeleteActivity", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDeleteActivity(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DeleteActivity", _args, result);
            }
        }
    }
}
